// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRunnerOKCode is the HTTP code returned for type GetRunnerOK
const GetRunnerOKCode int = 200

/*
GetRunnerOK OK

swagger:response getRunnerOK
*/
type GetRunnerOK struct {
}

// NewGetRunnerOK creates GetRunnerOK with default headers values
func NewGetRunnerOK() *GetRunnerOK {

	return &GetRunnerOK{}
}

// WriteResponse to the client
func (o *GetRunnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
